version: '3'

services:
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
  api:
    build: .
    restart: always
    command: sh -c "npm install && npm start"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      PORT: 3000
    depends_on:
      - db
